# Constants
height: 256
width: 256
channels: 1

train_batch_size: 4
valid_batch_size: 2
test_batch_size: 2
test_size: 0.15
valid_size: 0.15

# end_to_end, 2phases, only_phase2
training_type: 'end_to_end'
#training_type: '2phases'
#training_type: 'only_phase2'

max_slices: 57
shape:
  - 256
  - 256
  - 1

num_epochs: 20
learning_rate: 0.0001  # or use scientific notation as "1e-4"
inducing_points: 32
threshold: 0.5

num_classes: 1

projection_location: 'after_gp'

target_labels:
  - intraparenchymal

model_path: 'results/trained_model.pth'
device: 'cuda'
