# Constants
height: 224
width: 224
channels: 1

train_batch_size: 2
valid_batch_size: 2
test_batch_size: 2
test_size: 0.15
valid_size: 0.25

# end_to_end, 2phases, only_phase2
training_type: 'end_to_end'
#training_type: '2phases'
#training_type: 'only_phase2'
#training_type: 'dkl'

gp_model: 'single_task'

max_slices: 57
shape:
  - 224
  - 224
  - 1

num_epochs: 50
learning_rate: 0.0001  # or use scientific notation as "1e-4"
inducing_points: 50
threshold: 0.5

num_classes: 1

projection_location: 'after_gp'
projection_hidden_dim: 256
projection_output_dim: 128

attention_hidden_dim: 8

target_labels:
  - intraparenchymal

model_path: 'results/trained_model.pth'
device: 'cuda'
