dataset: 'rsna'
mode: 'train'

# Constants
height: 224
width: 224
channels: 1

train_batch_size: 4
valid_batch_size: 4
test_batch_size: 4
test_size: 0.15
valid_size: 0.25

# end_to_end, 2phases, only_phase2
training_type: 'end_to_end'
#training_type: 'cnn_att'

gp_model: 'single_task'
kernel_type: 'rbf'
model_type: 'resnet18'
#model_type: 'vgg'
contrastive_learning: 0

data_redundancy: 1
max_slices: 28
shape:
  - 224
  - 224
  - 1

num_epochs: 10
learning_rate: 0.0001
learning_rate_ngd: 0.01
inducing_points: 50
dropout: 0.25
threshold: 0.5
pos_weight: 25.0

num_classes: 6

projection_location: 'after_gp'
projection_hidden_dim: 256
projection_output_dim: 128

attention_hidden_dim: 64

target_labels:
  - intraparenchymal

model_path: 'results/trained_model.pth'
likelihood_path: 'results/likelihood.pth'
device: 'cuda'
