_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 1
                - 2
                - 19
                - 23
                - 55
            "4": 3.10.9
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 8
learning_rate:
    value: 0.0001
num_epochs:
    value: 30
